#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage: $0 <template-name> <dest>"
    exit
fi

tmpl_name="$1"
tmpl="templates/$tmpl_name"
dest="$2"

if [ ! -d "$tmpl" ]; then
    echo "Type not found"
    exit 1
fi

# Create the initial skeleton
cp -r project "$dest"

# Sync the parent templates over it
parent=`./tmpl-parent "$tmpl"`
while [ -n "$parent" ]; do
    echo "Syncing $parent..."
    rsync -qavz "templates/$parent/project/" "$dest"    
    parent=`./tmpl-parent "templates/$parent"`
done

# Finally, sync the selected template
echo "Syncing $tmpl_name..."
rsync -qavz "$tmpl/project/" "$dest"

# Process the templates
./run-templates "$dest" "$tmpl"
